spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres-authn:5432/authn_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_AUTHN_USER}
    password: ${POSTGRES_AUTHN_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8081

