spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://postgres-authn:5432/authn_db
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_AUTHN_USER}
    password: ${POSTGRES_AUTHN_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  data:
    redis:
      host: redis
      port: 6379
      password: ${REDIS_PASSWORD}
  kafka:
    bootstrap-servers: kafka:9092

server:
  port: 8081

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  access-token-expiry: ${JWT_ACCESS_TOKEN_EXPIRY:15m}
  refresh-token-expiry: ${JWT_REFRESH_TOKEN_EXPIRY:7d}
